name: SurvivalGamesMultiverse
main: me.lucasemanuel.survivalgamesmultiverse.Main
version: 0.9.4.1
depend: [WorldGuard, WorldEdit]

commands:
  sginfo:
    description: Show info concerning the plugin.
    usage: /<command> [worlds]
    permission: survivalgames.commands.sginfo
  sgdebug:
    description: Manages debug settings.
    usage: /<command> <set/listen> <true/false>
    permission: survivalgames.commands.sgdebug
  sglocation:
    description: Manages locations.
    usage: /<command> <set/save/clear> <main/arena>
    permission: survivalgames.commands.sglocation
  sgactivate:
    description: Activates the game for the given world.
    usage: /<command> <worldname>
    permission: survivalgames.commands.sgactivate
  sgreset:
    description: Resets the game for the given world.
    usage: /<command> <worldname>
    permission: survivalgames.commands.sgreset
  sgplayers:
    description: Lists all remaining players for the world the sender is in.
    usage: /<command> [worldname]
    permission: survivalgames.commands.sgplayers
  sgleave:
    description: Allows a player to leave the game.
    usage: /<command>
    permission: survivalgames.commands.sgleave
    
permissions:
  survivalgames.ignore.outsideofspawn:
    description: Players with this perm will not be teleported back to spawn if they aren't registered.
    default: op
  survivalgames.ignore.commandfilter:
    description: Players with this perm will be allowed to use any command while playing SG.
    default: op
  survivalgames.ignore.stats:
    description: Players with this perm will not recieve points in SG.
    default: false
  survivalgames.ignore.forcepumpkin:
    description: Players with this perm can remove their pumpkin helmet even if forcepumpkin is enabled in the config.
    default: op
  survivalgames.ignore.blockfilter:
    description: Allows a player to break/place blocks in a game world that hasnt started.
    default: op
  survivalgames.ignore.clearinv:
    description: Allows player to ignore inventory clearing upon joining SurvivalGames
    default: op
  survivalgames.signs.sginfo:
    description: Allows a player to register an sginfo sign.
    default: op