name: SurvivalGamesMultiverse
main: me.lucasemanuel.survivalgamesmultiverse.Main
version: 0.1

commands:
  sglocation:
    description: Manages locations.
    usage: /<command> <set/save/clear> <main/arena>
    permission: survivalgames.commands.sglocation
  sgactivate:
    description: Activates the game for the given world.
    usage: /<command> <worldname>
    permission: survivalgames.commands.sgactivate
  sgreset:
    description: Resets the game for the given world.
    usage: /<command> <worldname>
    permission: survivalgames.commands.sgreset
    
permissions:
  survivalgames.ignore.outsideofspawn:
    description: Players with this perm will not be teleported back to spawn if they arent registered.
    default: false